"""Add original_recipe_id for spicing it up

Revision ID: 26c037c489fe
Revises: bbbd4d14504e
Create Date: 2025-12-06 10:07:08.576297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c037c489fe'
down_revision = 'bbbd4d14504e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('original_recipe_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'recipes', 'recipes', ['original_recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    op.drop_column('recipes', 'original_recipe_id')
    # ### end Alembic commands ###
