"""Initial migration

Revision ID: 32319520597b
Revises: 
Create Date: 2025-03-05 19:56:19.087144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32319520597b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_tags', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe_tags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
