"""Add feedback table

Revision ID: 733ccfe289e1
Revises: 26c037c489fe
Create Date: 2025-12-06 15:00:19.974747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '733ccfe289e1'
down_revision = '26c037c489fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.create_table('feedback',
    #    sa.Column('id', sa.Integer(), nullable=False),
     #   sa.Column('user_id', sa.Integer(), nullable=False),
      #  sa.Column('type', sa.String(length=20), nullable=False),
       # sa.Column('title', sa.String(length=100), nullable=False),
        #sa.Column('description', sa.Text(), nullable=False),
        #sa.Column('status', sa.String(length=20), nullable=True),
        #sa.Column('created_at', sa.DateTime(), nullable=True),
        #sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        #sa.PrimaryKeyConstraint('id')
    #)
    pass
    # DELETED THE RECIPE CONSTRAINT LINE HERE
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # DELETED THE DROP CONSTRAINT LINE HERE
    op.drop_table('feedback')
    # ### end Alembic commands ###