"""Add featured column and site settings

Revision ID: af5b73f66adc
Revises: 733ccfe289e1
Create Date: 2025-12-07 14:51:55.902196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5b73f66adc'
down_revision = '733ccfe289e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'recipes', 'recipes', ['original_recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipes', type_='foreignkey')
    # ### end Alembic commands ###
