"""add feedback upvotes

Revision ID: b56b60b37600
Revises: af5b73f66adc
Create Date: 2025-12-07 15:09:18.951649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b56b60b37600'
down_revision = 'af5b73f66adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_upvotes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('feedback_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedback.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'feedback_id')
    )
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_table_column_ref_table', 'recipes', ['original_recipe_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('feedback_upvotes')
    # ### end Alembic commands ###
